language: go
dist: xenial
go:
- 1.11.x
node_js:
- '10.6.0'
sudo: required
install:
- nvm install 10.6.0
- npm install grunt-cli -g
- npm install --save-dev grunt string toml conzole
- wget https://github.com/spf13/hugo/releases/download/v0.20.2/hugo_0.20.2_Linux-64bit.tar.gz
- tar zxvf hugo_0.20.2_Linux-64bit.tar.gz
- mkdir -p $HOME/bin
- mv hugo_0.20.2_linux_amd64/hugo_0.20.2_linux_amd64 $HOME/bin/hugo
- echo $GOPATH
- export PATH=$PATH:$HOME/bin:$GOPATH/bin
- go get github.com/goadesign/goa
- go get github.com/goadesign/gorma
- cd tools/mdc && go get -v ./... && go build -o $HOME/bin/mdc && cd ../..
- cd tools/godoc2md && export GO111MODULE=on && go get -v ./... && go build -o $HOME/bin/godoc2md && cd ../..
- sudo pip install Pygments
script:
- make docs
- hugo
- grunt lunr-index
- make linkcheck
deploy:
  provider: gcs
  access_key_id: GOOGDIIIVPY7O6DG3PSZ
  secret_access_key:
    secure: MS6Hswy3dQGkJ/uXlll+2W6MoQfSLM8bZsHlWuwabe27Upw/Ah+UBUZNZBusER1Pn1St1kZ0anSjz63/tyKTfy6H2cJJ157g9k4mZGOMnpUmQhPJIeH5bF3e8rMYE/ry5hkiTt7f1bze6A/6a/nSvyhN8kaiP6j1k797GYBKiMArTzS72xiTmqtoDN1U4FMiDE8vDipzyy5lAnb8cVUSiMOl00++AeITW4mrfi2cUjVnxvuteBrkzZYujas74QON8zyNSsTRM62YGS6/pBSRWhoHaxIqqzwMm55OaJ55qWvbudC57jLc+c2FbX0mvL8rRy+rJVQm/4FAw0T0brxBTbwuEhAyer7fS9VueOiJWYI91F4yHINXU+vBvk8g4mV3pojk/9Jeqau4jK5CyU3OXWLItQcGvEspsR7GZif0c608LQGcVvQaYTtjpNltR0PHhRE1n+haWL84oa0qFgeSbDROpzss5f53Mfx4o15GHq8xtTbiJ8Wy64IcRofqoJl0r3UIu/T4VjhrgAbtLfTWkSs4Ma78SOSntv84QGjPE75DKuHUepn1wIWBtoGX8tL7cIwAaTpX9l9RGTDMHPHtZg91fGR3QgorFnjFiE5C1Ueql3DtSW5fLoPaQDaoxpUDgQAepDJoZCKo12j24ifbL3QKimMZURA1wuDFb9QnXmE=
  bucket: goa.design
  local-dir: public
  skip-cleanup: true
  acl: public-read
  cache-control: max-age=300
  on:
    repo: goadesign/goa.design
