name = "goa"
baseurl = "https://goa.design/"
description = "goa - Design First."
homepage = "https://goa.design"
license = "MIT"
licenselink = "https://github.com/goadesign/goa.design/blob/master/LICENSE"
disableKinds = ["taxonomy", "taxonomyTerm"]


uglyURLs = false
pluralizelisttitles = false
pygmentscodefences = true
pygmentsoptions = ""
pygmentsstyle = "friendly"
pygmentsuseclasses = false

[author]
name = "Raphael Simon and the goa contributors"
homepage = "https://github.com/goadesign/goa/graphs/contributors"

DefaultContentLanguage = "en"

[languages.en] 
weight = 1
title = "goa - Design First."
languageName = "English"

[[languages.en.menu.main]]
name = "Learn"
identifier = "learn"
url = "/learn"
weight = 1

[[languages.en.menu.main]]
name = "Design"
identifier = "design"
url = "/design/"
weight = 2

[[languages.en.menu.main]]
name = "Implement"
identifier = "implement"
url = "/implement/"
weight = 3

[[languages.en.menu.main]]
name = "Extend"
identifier = "extend"
url = "/extend"
weight = 4

[[languages.en.menu.main]]
name = "Blog"
identifier = "blog"
url = "/blog/"
weight = 5

[[languages.en.menu.v1]]
name = "Learn"
identifier = "learn.v1"
url = "/v1/learn"
weight = 1

[[languages.en.menu.v1]]
name = "Design"
identifier = "design.v1"
url = "/v1/design/"
weight = 2

[[languages.en.menu.v1]]
name = "Implement"
identifier = "implement.v1"
url = "/v1/implement/"
weight = 3

[[languages.en.menu.v1]]
name = "Extend"
identifier = "extend.v1"
url = "/v1/extend"
weight = 4

[[languages.en.menu.v1]]
name = "Blog"
identifier = "blog.v1"
url = "/v1/blog/"
weight = 5

[languages.ja] 
weight = 2
title = "goa - はじめにデザインを。"
languageName = "日本語"

[[languages.ja.menu.main]]
name = "学ぶ"
identifier = "learn"
url = "/ja/learn/"
weight = 1

[[languages.ja.menu.main]]
name = "デザイン"
identifier = "design"
url = "/ja/design/"
weight = 2

[[languages.ja.menu.main]]
name = "実装する"
identifier = "implement"
url = "/ja/implement/"
weight = 3

[[languages.ja.menu.main]]
name = "拡張する"
identifier = "extend"
url = "/ja/plugins/"
weight = 4

[[languages.ja.menu.main]]
name = "ブログ"
identifier = "blog"
url = "/ja/blog/"
weight = 5

[[languages.ja.menu.v1]]
name = "学ぶ"
identifier = "learn.v1"
url = "/v1/ja/learn/"
weight = 1

[[languages.ja.menu.v1]]
name = "デザイン"
identifier = "design.v1"
url = "/v1/ja/design/"
weight = 2

[[languages.ja.menu.v1]]
name = "実装する"
identifier = "implement.v1"
url = "/v1/ja/implement/"
weight = 3

[[languages.ja.menu.v1]]
name = "拡張する"
identifier = "extend.v1"
url = "/v1/ja/plugins/"
weight = 4

[[languages.ja.menu.v1]]
name = "ブログ"
identifier = "blog.v1"
url = "/v1/ja/blog/"
weight = 5
